services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: chatnshop-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__API_KEY: qdrant-secret-key

  redis:
    image: redis:7-alpine
    container_name: chatns-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --appendonly yes
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__API_KEY=mykey@123
    restart: unless-stopped

  intent-api:
    build: .
    container_name: chatnshop-intent-api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_storage:
