version: '3.8'

services:
  # ==============================
  # Qdrant Vector Database
  # ==============================
  qdrant:
    image: qdrant/qdrant:latest
    container_name: chatnshop-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      # ✅ Fixed endpoint to /healthz (new version uses this)
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ==============================
  # Intent Classification API
  # ==============================
  intent-api:
    build: .
    container_name: chatnshop-intent-api
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./app/ai/intent_classification/keywords:/app/app/ai/intent_classification/keywords
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s

# ==============================
# Persistent Storage
# ==============================
volumes:
  qdrant_storage:
