from enum import Enum

class IntentCategory(Enum):
    # =============================================================================
    # ESSENTIAL ECOMMERCE CATEGORIES (10 Core Categories)
    # =============================================================================
    
    # 1. Core Product Discovery & Search
    SEARCH_DISCOVERY = "SEARCH_DISCOVERY"
    
    # 2. Product Information & Details
    PRODUCT_DETAILS = "PRODUCT_DETAILS"
    
    # 3. Shopping Cart & Wishlist Management
    CART_WISHLIST = "CART_WISHLIST"
    
    # 4. Checkout & Payment Processing
    CHECKOUT_PAYMENT = "CHECKOUT_PAYMENT"
    
    # 5. Order Management & Fulfillment
    ORDERS_FULFILLMENT = "ORDERS_FULFILLMENT"
    
    # 6. User Account & Profile Management
    ACCOUNT_PROFILE = "ACCOUNT_PROFILE"
    
    # 7. Customer Support & Help
    SUPPORT_HELP = "SUPPORT_HELP"
    
    # 8. Promotions, Offers & Loyalty Programs
    PROMOTIONS_LOYALTY = "PROMOTIONS_LOYALTY"
    
    # 9. Returns & Refunds
    RETURNS_REFUNDS = "RETURNS_REFUNDS"
    
    # 10. Product Reviews & Ratings
    REVIEWS_RATINGS = "REVIEWS_RATINGS"
    
    # =============================================================================
    # COMMENTED OUT CATEGORIES (Not Essential for Basic Ecommerce Chatbot)
    # =============================================================================
    # These categories are either too specialized, administrative, or not required
    # for a basic ecommerce AI chatbot. They can be uncommented and implemented
    # later as the chatbot evolves and requires more advanced functionality.
    
    # NOTIFICATIONS_SUBSCRIPTIONS = "NOTIFICATIONS_SUBSCRIPTIONS"
    # SELLER_MARKETPLACE = "SELLER_MARKETPLACE"
    # ANALYTICS_TRACKING = "ANALYTICS_TRACKING"
    # PERSONALIZATION = "PERSONALIZATION"
    # SEARCH_ADVANCED = "SEARCH_ADVANCED"
    # VOICE_BOT = "VOICE_BOT"
    # NAVIGATION = "NAVIGATION"
    # FILES_DOWNLOADS = "FILES_DOWNLOADS"
    # LEGAL_PRIVACY = "LEGAL_PRIVACY"
    # ADMIN_MODERATION = "ADMIN_MODERATION"
    # INTEGRATIONS = "INTEGRATIONS"
    # OFFLINE_STORES = "OFFLINE_STORES"
    # FINANCE_INVOICING = "FINANCE_INVOICING"
    # MESSAGING = "MESSAGING"
    # EXPERIMENTS = "EXPERIMENTS"
    # B2B_ENTERPRISE = "B2B_ENTERPRISE"
    # LOYALTY_MEMBERSHIP = "LOYALTY_MEMBERSHIP"
    # SEARCH_INSIGHTS = "SEARCH_INSIGHTS"
    # SEO_LINKS = "SEO_LINKS"
    # HELPERS_FALLBACK = "HELPERS_FALLBACK"
    # FINE_SEARCH = "FINE_SEARCH"
    # CART_EDGE_CASES = "CART_EDGE_CASES"
    # ORDER_SUBSCRIPTIONS = "ORDER_SUBSCRIPTIONS"
    # SECURITY_FRAUD = "SECURITY_FRAUD"
    # DATA_BACKUPS = "DATA_BACKUPS"
    # SHOPPING_ASSISTANT = "SHOPPING_ASSISTANT"
    # TAX_INTERNATIONAL = "TAX_INTERNATIONAL"
    # PAYMENTS_ADVANCED = "PAYMENTS_ADVANCED"
    # OFFLINE_NOTIFICATIONS = "OFFLINE_NOTIFICATIONS"
    # PRODUCT_LIFECYCLE = "PRODUCT_LIFECYCLE"
    # COUPONS_VOUCHERS = "COUPONS_VOUCHERS"
    # FEEDBACK_SURVEYS = "FEEDBACK_SURVEYS"
    # DEVICE_APP = "DEVICE_APP"
    # CONTENT_GUIDES = "CONTENT_GUIDES"
    # SOCIAL_FEATURES = "SOCIAL_FEATURES"
    # BILLING_ACCOUNTING = "BILLING_ACCOUNTING"
    # QA_DEVOPS = "QA_DEVOPS"
    # INVENTORY = "INVENTORY"
    # GUIDANCE = "GUIDANCE"
    # MISCELLANEOUS = "MISCELLANEOUS"
    # UNKNOWN = "UNKNOWN"


class ActionCode:
    # =============================================================================
    # STREAMLINED ECOMMERCE ACTION CODES (50 Essential Codes)
    # =============================================================================
    # Reduced from 197 codes to 50 essential codes for a starting ecommerce project
    # Focus on core functionality while maintaining all 10 categories
    
    # 1️⃣ SEARCH & DISCOVERY (8 codes)
    SEARCH_PRODUCT = "SEARCH_PRODUCT"
    SEARCH_CATEGORY = "SEARCH_CATEGORY"
    SEARCH_BRAND = "SEARCH_BRAND"
    SEARCH_PRICE_RANGE = "SEARCH_PRICE_RANGE"
    FILTER_PRICE = "FILTER_PRICE"
    FILTER_RATING = "FILTER_RATING"
    FILTER_AVAILABILITY = "FILTER_AVAILABILITY"
    SORT_PRICE = "SORT_PRICE"
    SORT_POPULARITY = "SORT_POPULARITY"

    # 2️⃣ PRODUCT DETAILS (6 codes)
    PRODUCT_INFO = "PRODUCT_INFO"
    PRODUCT_DETAILS = "PRODUCT_DETAILS"
    PRODUCT_AVAILABILITY = "PRODUCT_AVAILABILITY"
    PRODUCT_PRICE = "PRODUCT_PRICE"
    PRODUCT_VARIANTS = "PRODUCT_VARIANTS"
    PRODUCT_REVIEWS = "PRODUCT_REVIEWS"

    # 3️⃣ CART & WISHLIST (8 codes)
    ADD_TO_CART = "ADD_TO_CART"
    REMOVE_FROM_CART = "REMOVE_FROM_CART"
    UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY"
    VIEW_CART = "VIEW_CART"
    ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
    REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"
    VIEW_WISHLIST = "VIEW_WISHLIST"
    APPLY_COUPON = "APPLY_COUPON"

    # 4️⃣ CHECKOUT & PAYMENT (7 codes)
    CHECKOUT_INITIATE = "CHECKOUT_INITIATE"
    CHECKOUT_CONFIRM = "CHECKOUT_CONFIRM"
    ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS"
    UPDATE_ADDRESS = "UPDATE_ADDRESS"
    CHANGE_ADDRESS = "CHANGE_ADDRESS"
    PAYMENT_OPTIONS = "PAYMENT_OPTIONS"
    CHANGE_PAYMENT_METHOD = "CHANGE_PAYMENT_METHOD"

    # 5️⃣ ORDERS & FULFILLMENT (7 codes)
    ORDER_STATUS = "ORDER_STATUS"
    ORDER_HISTORY = "ORDER_HISTORY"
    ORDER_CANCEL = "ORDER_CANCEL"
    TRACK_SHIPMENT = "TRACK_SHIPMENT"
    DELIVERY_STATUS = "DELIVERY_STATUS"
    DELIVERY_ESTIMATE = "DELIVERY_ESTIMATE"
    REORDER = "REORDER"

    # 6️⃣ ACCOUNT & PROFILE (5 codes)
    CREATE_ACCOUNT = "CREATE_ACCOUNT"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    FORGOT_PASSWORD = "FORGOT_PASSWORD"
    RESET_PASSWORD = "RESET_PASSWORD"

    # 7️⃣ SUPPORT & HELP (5 codes)
    CONTACT_SUPPORT = "CONTACT_SUPPORT"
    HELP_GENERAL = "HELP_GENERAL"
    REPORT_ISSUE = "REPORT_ISSUE"
    FAQ_SHIPPING = "FAQ_SHIPPING"
    FAQ_PAYMENT = "FAQ_PAYMENT"

    # 8️⃣ PROMOTIONS & LOYALTY (4 codes)
    VIEW_PROMOTIONS = "VIEW_PROMOTIONS"
    VIEW_COUPONS = "VIEW_COUPONS"
    APPLY_PROMO = "APPLY_PROMO"
    VIEW_SALE_COLLECTION = "VIEW_SALE_COLLECTION"

    # 9️⃣ RETURNS & REFUNDS (5 codes)
    VIEW_RETURN_POLICY = "VIEW_RETURN_POLICY"
    INITIATE_RETURN = "INITIATE_RETURN"
    RETURN_STATUS = "RETURN_STATUS"
    REFUND_REQUEST = "REFUND_REQUEST"
    TRACK_RETURN = "TRACK_RETURN"

    # 🔟 REVIEWS & RATINGS (5 codes)
    ADD_REVIEW = "ADD_REVIEW"
    VIEW_REVIEWS = "VIEW_REVIEWS"
    PRODUCT_AVERAGE_REVIEW = "PRODUCT_AVERAGE_REVIEW"
    EDIT_REVIEW = "EDIT_REVIEW"
    DELETE_REVIEW = "DELETE_REVIEW"

    # =============================================================================
    # REMOVED ACTION CODES (Available for Future Expansion)
    # =============================================================================
    # The following action codes were removed to streamline the system to 50 essential codes.
    # They can be re-added as the ecommerce platform grows and requires more advanced functionality.
    # 
    # Removed categories include:
    # - Advanced search filters (color, size, material, trending, featured)
    # - Detailed product information (dimensions, weight, SKU, FAQ, video)
    # - Advanced cart features (save for later, gift wrap, notes, recently viewed)
    # - Complex payment states and gift card functionality
    # - Detailed order management (invoices, shipping costs, delivery scheduling)
    # - Advanced account features (2FA, social login, email verification, profile updates)
    # - Specialized support features (live chat, call support, multiple FAQ categories)
    # - Loyalty programs (points, rewards, price alerts, flash sales)
    # - Warranty operations and return eligibility checks
    # - Review moderation features (flagging, recommendations)
    
    # 10️⃣ SELLER, MARKETPLACE & CATALOG (10.0)
    # VIEW_SELLER_INFO = "VIEW_SELLER_INFO"
    # CONTACT_SELLER = "CONTACT_SELLER"
    # VIEW_SELLER_RATINGS = "VIEW_SELLER_RATINGS"
    # SELLER_POLICIES = "SELLER_POLICIES"
    # BULK_ORDER = "BULK_ORDER"
    # WHOLESALE_INQUIRY = "WHOLESALE_INQUIRY"
    # CORPORATE_ORDER = "CORPORATE_ORDER"
    # LIST_PRODUCT = "LIST_PRODUCT"
    # UNLIST_PRODUCT = "UNLIST_PRODUCT"
    # UPDATE_PRODUCT_LISTING = "UPDATE_PRODUCT_LISTING"
    # VERIFY_SELLER = "VERIFY_SELLER"

    # 13️⃣ ANALYTICS, TRACKING & METRICS (13.0)
    # TRACK_USER_ACTION = "TRACK_USER_ACTION"
    # TRACK_SEARCH_QUERY = "TRACK_SEARCH_QUERY"
    # TRACK_CART_ABANDONMENT = "TRACK_CART_ABANDONMENT"
    # VIEW_ANALYTICS = "VIEW_ANALYTICS"
    # EXPORT_ANALYTICS = "EXPORT_ANALYTICS"
    # LISTEN_BEHAVIOR = "LISTEN_BEHAVIOR"

    # 14️⃣ ACCOUNT PREFERENCES & PERSONALIZATION (14.0)
    # SET_LANGUAGE = "SET_LANGUAGE"
    # SET_CURRENCY = "SET_CURRENCY"
    # SET_ADDRESS_PREFERENCE = "SET_ADDRESS_PREFERENCE"
    # SET_PAYMENT_PREFERENCE = "SET_PAYMENT_PREFERENCE"
    # MANAGE_ADDRESSES = "MANAGE_ADDRESSES"
    # PREFERENCES_EXPORT = "PREFERENCES_EXPORT"
    # PREFERENCES_IMPORT = "PREFERENCES_IMPORT"
    # PERSONAL_PROFILE_SUMMARY = "PERSONAL_PROFILE_SUMMARY"

    # 15️⃣ SEARCH ADVANCED (15.0)
    # SEARCH_ADVANCED = "SEARCH_ADVANCED"
    # SEARCH_FUZZY = "SEARCH_FUZZY"
    # SEARCH_PHRASE = "SEARCH_PHRASE"
    # SEARCH_EXCLUDE = "SEARCH_EXCLUDE"
    # SEARCH_BOOLEAN = "SEARCH_BOOLEAN"
    # SEARCH_CUSTOM_FILTER = "SEARCH_CUSTOM_FILTER"
    # SEARCH_BY_SKU = "SEARCH_BY_SKU"

    # 16️⃣ VOICE, ASSISTANTS & BOT (16.0)
    # START_VOICE_SESSION = "START_VOICE_SESSION"
    # END_VOICE_SESSION = "END_VOICE_SESSION"
    # VOICE_HELP = "VOICE_HELP"
    # BOT_HANDOFF = "BOT_HANDOFF"
    # BOT_INTENT_CLARIFY = "BOT_INTENT_CLARIFY"
    # BOT_FALLBACK = "BOT_FALLBACK"

    # 17️⃣ UI & NAVIGATION (17.0)
    # NAV_HOME = "NAV_HOME"
    # NAV_CATEGORY = "NAV_CATEGORY"
    # NAV_CART = "NAV_CART"
    # NAV_WISHLIST = "NAV_WISHLIST"
    # NAV_ORDERS = "NAV_ORDERS"
    # NAV_PROFILE = "NAV_PROFILE"
    # NAV_SEARCH = "NAV_SEARCH"
    # NAV_OFFERS = "NAV_OFFERS"
    # NAV_HELP = "NAV_HELP"

    # 18️⃣ FILES, DOWNLOADS & ASSETS (18.0)
    # DOWNLOAD_INVOICE = "DOWNLOAD_INVOICE"
    # DOWNLOAD_MANUAL = "DOWNLOAD_MANUAL"
    # DOWNLOAD_RECEIPT = "DOWNLOAD_RECEIPT"
    # APP_DOWNLOAD = "APP_DOWNLOAD"
    # SHARE_PRODUCT_LINK = "SHARE_PRODUCT_LINK"

    # 19️⃣ PRIVACY, TERMS & LEGAL (19.0)
    # PRIVACY_POLICY = "PRIVACY_POLICY"
    # TERMS_AND_CONDITIONS = "TERMS_AND_CONDITIONS"
    # DATA_REQUEST = "DATA_REQUEST"
    # DATA_DELETE_REQUEST = "DATA_DELETE_REQUEST"
    # COOKIE_PREFERENCES = "COOKIE_PREFERENCES"

    # 20️⃣ ADMIN, MODERATION & SAFETY (20.0)
    # FLAG_CONTENT = "FLAG_CONTENT"
    # REVIEW_FLAGGED_CONTENT = "REVIEW_FLAGGED_CONTENT"
    # BAN_USER = "BAN_USER"
    # UNBAN_USER = "UNBAN_USER"
    # GRANT_ADMIN = "GRANT_ADMIN"
    # REVOKE_ADMIN = "REVOKE_ADMIN"
    # VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS"
    # EXPORT_AUDIT_LOGS = "EXPORT_AUDIT_LOGS"
    # MODERATION_ACTION = "MODERATION_ACTION"

    # 21️⃣ INTEGRATIONS & THIRD-PARTY (21.0)
    # CONNECT_PAYMENT_GATEWAY = "CONNECT_PAYMENT_GATEWAY"
    # DISCONNECT_PAYMENT_GATEWAY = "DISCONNECT_PAYMENT_GATEWAY"
    # CONNECT_SHIPPING_PROVIDER = "CONNECT_SHIPPING_PROVIDER"
    # DISCONNECT_SHIPPING_PROVIDER = "DISCONNECT_SHIPPING_PROVIDER"
    # SYNC_INVENTORY = "SYNC_INVENTORY"
    # SYNC_ORDERS = "SYNC_ORDERS"

    # 22️⃣ OFFLINE, STORES & PICKUP (22.0)
    # STORE_LOCATOR = "STORE_LOCATOR"
    # CHECK_STORE_STOCK = "CHECK_STORE_STOCK"
    # RESERVE_IN_STORE = "RESERVE_IN_STORE"
    # SCHEDULE_PICKUP = "SCHEDULE_PICKUP"
    # CANCEL_PICKUP = "CANCEL_PICKUP"

    # 23️⃣ MARKETPLACE FINANCE & INVOICING (23.0)
    # REQUEST_INVOICE = "REQUEST_INVOICE"
    # SUBMIT_TAX_INFO = "SUBMIT_TAX_INFO"
    # VIEW_PAYOUTS = "VIEW_PAYOUTS"
    # REQUEST_PAYOUT = "REQUEST_PAYOUT"

    # 24️⃣ MESSAGING & COMMUNICATION (24.0)
    # SEND_MESSAGE_TO_SELLER = "SEND_MESSAGE_TO_SELLER"
    # VIEW_MESSAGES = "VIEW_MESSAGES"
    # DELETE_MESSAGE = "DELETE_MESSAGE"
    # MARK_MESSAGE_READ = "MARK_MESSAGE_READ"
    # MARK_MESSAGE_UNREAD = "MARK_MESSAGE_UNREAD"

    # 25️⃣ EXPERIMENTS, FEATURES & FLAGS (25.0)
    # ENABLE_EXPERIMENT = "ENABLE_EXPERIMENT"
    # DISABLE_EXPERIMENT = "DISABLE_EXPERIMENT"
    # GET_EXPERIMENT_STATUS = "GET_EXPERIMENT_STATUS"

    # 26️⃣ B2B & ENTERPRISE (26.0)
    # REQUEST_CORPORATE_ACCOUNT = "REQUEST_CORPORATE_ACCOUNT"
    # VIEW_ENTERPRISE_PRICING = "VIEW_ENTERPRISE_PRICING"
    # REQUEST_DEMO = "REQUEST_DEMO"
    # ENTERPRISE_BULK_ORDER = "ENTERPRISE_BULK_ORDER"

    # 27️⃣ LOYALTY & MEMBERSHIP (27.0)
    # VIEW_MEMBERSHIP = "VIEW_MEMBERSHIP"
    # JOIN_MEMBERSHIP = "JOIN_MEMBERSHIP"
    # LEAVE_MEMBERSHIP = "LEAVE_MEMBERSHIP"
    # MEMBERSHIP_BENEFITS = "MEMBERSHIP_BENEFITS"
    # MEMBERSHIP_STATUS = "MEMBERSHIP_STATUS"

    # 28️⃣ SEARCH INSIGHTS & AUTOCOMPLETE (28.0)
    # AUTOCOMPLETE_SUGGESTIONS = "AUTOCOMPLETE_SUGGESTIONS"
    # SEARCH_SUGGESTION_CLICK = "SEARCH_SUGGESTION_CLICK"
    # POPULAR_SEARCH_TERMS = "POPULAR_SEARCH_TERMS"

    # 29️⃣ SEO & LINKS (29.0)
    # REQUEST_SEO_FRIENDLY_URL = "REQUEST_SEO_FRIENDLY_URL"
    # REPORT_BROKEN_LINK = "REPORT_BROKEN_LINK"

    # 30️⃣ HELPERS, FALLBACKS & UNKNOWN (30.0)
    # HELP_CONTEXTUAL = "HELP_CONTEXTUAL"
    # HELP_INTENT_EXAMPLE = "HELP_INTENT_EXAMPLE"
    # BOT_GREETING = "BOT_GREETING"
    # BOT_GOODBYE = "BOT_GOODBYE"
    # BOT_THANKS = "BOT_THANKS"
    # BOT_ERROR = "BOT_ERROR"
    # BOT_CONFIRMATION = "BOT_CONFIRMATION"
    # BOT_PROMPT_RETRY = "BOT_PROMPT_RETRY"
    # BOT_PROMPT_CONFIRM = "BOT_PROMPT_CONFIRM"

    # 31️⃣ VERY FINE-GRAINED SEARCH & USER ACTIONS (31.0)
    # SEARCH_CATEGORY_SUB = "SEARCH_CATEGORY_SUB"
    # SEARCH_BY_COLLECTION = "SEARCH_BY_COLLECTION"
    # SEARCH_BY_MATERIAL = "SEARCH_BY_MATERIAL"
    # SEARCH_BY_THEME = "SEARCH_BY_THEME"
    # SEARCH_BY_SEASON = "SEARCH_BY_SEASON"
    # SEARCH_BY_OCCASION = "SEARCH_BY_OCCASION"
    # FILTER_BY_RETURNABLE = "FILTER_BY_RETURNABLE"
    # FILTER_BY_FREE_SHIPPING = "FILTER_BY_FREE_SHIPPING"
    # FILTER_BY_EXCHANGE = "FILTER_BY_EXCHANGE"

    # 32️⃣ CART & CHECKOUT EDGE CASES (32.0)
    # RESOLVE_CART_CONFLICT = "RESOLVE_CART_CONFLICT"
    # MERGE_CARTS = "MERGE_CARTS"
    # SAVE_CART = "SAVE_CART"
    # RESTORE_SAVED_CART = "RESTORE_SAVED_CART"
    # PRICING_DISCREPANCY = "PRICING_DISCREPANCY"
    # APPLY_AUTO_DISCOUNT = "APPLY_AUTO_DISCOUNT"

    # 33️⃣ ORDER SUBSCRIPTIONS & RECURRING (33.0)
    # SUBSCRIBE_PRODUCT = "SUBSCRIBE_PRODUCT"
    # UNSUBSCRIBE_PRODUCT = "UNSUBSCRIBE_PRODUCT"
    # SUBSCRIPTION_STATUS = "SUBSCRIPTION_STATUS"
    # MANAGE_SUBSCRIPTION = "MANAGE_SUBSCRIPTION"
    # PAUSE_SUBSCRIPTION = "PAUSE_SUBSCRIPTION"
    # RESUME_SUBSCRIPTION = "RESUME_SUBSCRIPTION"

    # 34️⃣ SECURITY & FRAUD (34.0)
    # REPORT_FRAUD = "REPORT_FRAUD"
    # FRAUD_DETECTION_HELP = "FRAUD_DETECTION_HELP"
    # LOCK_ACCOUNT = "LOCK_ACCOUNT"
    # UNLOCK_ACCOUNT = "UNLOCK_ACCOUNT"

    # 35️⃣ DATA, EXPORTS & BACKUPS (35.0)
    # EXPORT_ORDERS = "EXPORT_ORDERS"
    # EXPORT_CUSTOMERS = "EXPORT_CUSTOMERS"
    # EXPORT_PRODUCTS = "EXPORT_PRODUCTS"
    # BACKUP_DATA = "BACKUP_DATA"
    # RESTORE_DATA = "RESTORE_DATA"

    # 36️⃣ PERSONAL SHOPPING ASSISTANT (36.0)
    # ASSISTANT_PROFILE_SETUP = "ASSISTANT_PROFILE_SETUP"
    # ASSISTANT_SAVE_PREFERENCES = "ASSISTANT_SAVE_PREFERENCES"
    # ASSISTANT_SUGGEST = "ASSISTANT_SUGGEST"
    # ASSISTANT_REMINDER = "ASSISTANT_REMINDER"

    # 37️⃣ INTERNATIONALIZATION & TAX (37.0)
    # CHECK_TAX = "CHECK_TAX"
    # VIEW_TAX_DETAILS = "VIEW_TAX_DETAILS"
    # SET_TAX_RESIDENCE = "SET_TAX_RESIDENCE"
    # CHECK_IMPORT_DUTY = "CHECK_IMPORT_DUTY"

    # 38️⃣ PAYMENTS — ADVANCED (38.0)
    # SPLIT_PAYMENT = "SPLIT_PAYMENT"
    # EMI_OPTIONS = "EMI_OPTIONS"
    # APPLY_EMI = "APPLY_EMI"
    # CANCEL_EMI = "CANCEL_EMI"
    # VERIFY_BANK_ACCOUNT = "VERIFY_BANK_ACCOUNT"

    # 39️⃣ OFFLINE MESSAGING & NOTIFICATIONS (39.0)
    # SCHEDULE_NOTIFICATION = "SCHEDULE_NOTIFICATION"
    # CANCEL_NOTIFICATION = "CANCEL_NOTIFICATION"
    # VIEW_NOTIFICATION_HISTORY = "VIEW_NOTIFICATION_HISTORY"

    # 40️⃣ PRODUCT LIFECYCLE (40.0)
    # PRODUCT_UPLOAD = "PRODUCT_UPLOAD"
    # PRODUCT_UPDATE = "PRODUCT_UPDATE"
    # PRODUCT_DELETE = "PRODUCT_DELETE"
    # PRODUCT_ARCHIVE = "PRODUCT_ARCHIVE"
    # PRODUCT_RESTORE = "PRODUCT_RESTORE"

    # 41️⃣ COUPONS & VOUCHERS (41.0)
    # CREATE_COUPON = "CREATE_COUPON"
    # EDIT_COUPON = "EDIT_COUPON"
    # DELETE_COUPON = "DELETE_COUPON"
    # VALIDATE_COUPON = "VALIDATE_COUPON"
    # CHECK_COUPON_STATUS = "CHECK_COUPON_STATUS"

    # 42️⃣ FEEDBACK & SURVEYS (42.0)
    # SUBMIT_SURVEY = "SUBMIT_SURVEY"
    # VIEW_SURVEY_RESULTS = "VIEW_SURVEY_RESULTS"
    # REQUEST_FEEDBACK = "REQUEST_FEEDBACK"

    # 43️⃣ DEVICE & APP (43.0)
    # REPORT_APP_ISSUE = "REPORT_APP_ISSUE"
    # APP_FEEDBACK = "APP_FEEDBACK"
    # CHECK_APP_VERSION = "CHECK_APP_VERSION"
    # REPORT_CRASH = "REPORT_CRASH"

    # 44️⃣ CONTENT, BLOG & GUIDES (44.0)
    # VIEW_BLOG = "VIEW_BLOG"
    # SEARCH_BLOG = "SEARCH_BLOG"
    # SUBMIT_BLOG_COMMENT = "SUBMIT_BLOG_COMMENT"
    # VIEW_GUIDE = "VIEW_GUIDE"

    # 45️⃣ COOPERATIVE & SOCIAL FEATURES (45.0)
    # SHARE_WISHLIST = "SHARE_WISHLIST"
    # FOLLOW_BRAND = "FOLLOW_BRAND"
    # UNFOLLOW_BRAND = "UNFOLLOW_BRAND"
    # INVITE_FRIEND = "INVITE_FRIEND"
    # APPLY_REFERRAL = "APPLY_REFERRAL"
    # VIEW_REFERRAL_STATUS = "VIEW_REFERRAL_STATUS"

    # 46️⃣ BILLING & ACCOUNTING (46.0)
    # VIEW_BILLING_HISTORY = "VIEW_BILLING_HISTORY"
    # UPDATE_BILLING_INFO = "UPDATE_BILLING_INFO"
    # DOWNLOAD_BILL = "DOWNLOAD_BILL"

    # 47️⃣ QA, TEST & DEVOPS (47.0)
    # TRIGGER_SMOKE_TEST = "TRIGGER_SMOKE_TEST"
    # TRIGGER_LOAD_TEST = "TRIGGER_LOAD_TEST"
    # DEPLOY_ROLLBACK = "DEPLOY_ROLLBACK"
    # VIEW_DEPLOYMENT_STATUS = "VIEW_DEPLOYMENT_STATUS"

    # 48️⃣ ASSORTMENT & INVENTORY (48.0)
    # VIEW_INVENTORY_LEVELS = "VIEW_INVENTORY_LEVELS"
    # UPDATE_INVENTORY = "UPDATE_INVENTORY"
    # REPORT_STOCK_ISSUE = "REPORT_STOCK_ISSUE"
    # INVENTORY_RECONCILE = "INVENTORY_RECONCILE"

    # 49️⃣ HELP & GUIDANCE (49.0)
    # GET_START_GUIDE = "GET_START_GUIDE"
    # GET_RETURN_INSTRUCTIONS = "GET_RETURN_INSTRUCTIONS"
    # GET_WARRANTY_INSTRUCTIONS = "GET_WARRANTY_INSTRUCTIONS"

    # 50️⃣ MISCELLANEOUS VERY FINE-GRAINED (50.0)
    # PING = "PING"
    # HEALTH_CHECK = "HEALTH_CHECK"
    # USER_SESSION_INFO = "USER_SESSION_INFO"
    # TIMEZONE_SET = "TIMEZONE_SET"
    # LOCALE_SET = "LOCALE_SET"

    # FINAL: Unknown / fallback
    # UNKNOWN = "UNKNOWN"

class IntentPriority(Enum):
    """Priority levels for intent processing."""
    CRITICAL = 1    # Checkout, payment, critical actions
    HIGH = 2        # Search, cart operations
    MEDIUM = 3      # Browsing, recommendations
    LOW = 4         # General interaction
    FALLBACK = 5    # Unknown intents


class EntityType(Enum):
    """Types of entities that can be extracted from user input."""
    PRODUCT_QUERY = "product_query"
    PRODUCT_ID = "product_id"
    CATEGORY = "category"
    BRAND = "brand"
    PRICE_RANGE = "price_range"
    QUANTITY = "quantity"
    ORDER_ID = "order_id"
    COUPON_CODE = "coupon_code"
    PAYMENT_METHOD = "payment_method"
    FILTER_CRITERIA = "filter_criteria"
    SORT_CRITERIA = "sort_criteria"
    SIZE = "size"
    COLOR = "color"
    DATE_RANGE = "date_range"
    REASON = "reason"
    URGENCY = "urgency"
    QUESTION = "question"
    TOPIC = "topic"
    ISSUE_TYPE = "issue_type"
    BUDGET = "budget"
    PREFERENCES = "preferences"
    
    # Additional essential entities for ecommerce
    ADDRESS = "address"
    PHONE_NUMBER = "phone_number"
    EMAIL = "email"
    REVIEW_RATING = "review_rating"
    RETURN_REASON = "return_reason"
    SHIPPING_METHOD = "shipping_method"
    USER_ID = "user_id"