from enum import Enum
from typing import Dict

# INTENT TAXONOMY (~320 intents) - Hierarchical, numbered for documentation & stakeholder review
class Intent(str, Enum):
    # 1️⃣ SEARCH & DISCOVERY (1.0)
    # 1.1 Product Search (1.1)
    SEARCH_PRODUCT = "SEARCH_PRODUCT"
    SEARCH_CATEGORY = "SEARCH_CATEGORY"
    SEARCH_BRAND = "SEARCH_BRAND"
    SEARCH_PRICE_RANGE = "SEARCH_PRICE_RANGE"
    SEARCH_COLOR = "SEARCH_COLOR"
    SEARCH_SIZE = "SEARCH_SIZE"
    SEARCH_RATING = "SEARCH_RATING"
    SEARCH_DISCOUNT = "SEARCH_DISCOUNT"
    SEARCH_BY_IMAGE = "SEARCH_BY_IMAGE"
    SEARCH_BY_VOICE = "SEARCH_BY_VOICE"
    SEARCH_TRENDING = "SEARCH_TRENDING"
    SEARCH_RECENT = "SEARCH_RECENT"
    SEARCH_NEARBY = "SEARCH_NEARBY"
    SEARCH_SIMILAR = "SEARCH_SIMILAR"
    SEARCH_SAVED = "SEARCH_SAVED"
    SEARCH_FEATURED = "SEARCH_FEATURED"
    SEARCH_NEW_ARRIVALS = "SEARCH_NEW_ARRIVALS"
    SEARCH_BESTSELLERS = "SEARCH_BESTSELLERS"
    SEARCH_ON_SALE = "SEARCH_ON_SALE"
    SEARCH_EXACT_MATCH = "SEARCH_EXACT_MATCH"

    # 1.2 Discovery & Recommendations (1.2)
    PRODUCT_RECOMMENDATION = "PRODUCT_RECOMMENDATION"
    PERSONALIZED_RECOMMENDATIONS = "PERSONALIZED_RECOMMENDATIONS"
    RECOMMEND_FOR_OCCASION = "RECOMMEND_FOR_OCCASION"
    RECOMMEND_SIMILAR = "RECOMMEND_SIMILAR"
    RECOMMEND_COMPLEMENTS = "RECOMMEND_COMPLEMENTS"
    VIEW_RECOMMENDED = "VIEW_RECOMMENDED"
    BROWSE_CURATED_LIST = "BROWSE_CURATED_LIST"
    VIEW_FEATURED = "VIEW_FEATURED"
    VIEW_PROMOTIONS = "VIEW_PROMOTIONS"

    # 1.3 Search Filters & Facets (1.3)
    FILTER_PRICE = "FILTER_PRICE"
    FILTER_RATING = "FILTER_RATING"
    FILTER_BRAND = "FILTER_BRAND"
    FILTER_AVAILABILITY = "FILTER_AVAILABILITY"
    FILTER_COLOR = "FILTER_COLOR"
    FILTER_SIZE = "FILTER_SIZE"
    FILTER_DISCOUNT = "FILTER_DISCOUNT"
    APPLY_FILTERS = "APPLY_FILTERS"
    REMOVE_FILTERS = "REMOVE_FILTERS"
    CLEAR_FILTER = "CLEAR_FILTER"

    # 1.4 Sorting & View Options (1.4)
    SORT_PRICE = "SORT_PRICE"
    SORT_POPULARITY = "SORT_POPULARITY"
    SORT_NEWEST = "SORT_NEWEST"
    SORT_RATING = "SORT_RATING"
    VIEW_GRID = "VIEW_GRID"
    VIEW_LIST = "VIEW_LIST"

    # 2️⃣ PRODUCT DETAILS & COMPARISON (2.0)
    PRODUCT_INFO = "PRODUCT_INFO"
    PRODUCT_DETAILS = "PRODUCT_DETAILS"
    PRODUCT_AVAILABILITY = "PRODUCT_AVAILABILITY"
    PRODUCT_PRICE = "PRODUCT_PRICE"
    PRODUCT_IMAGES = "PRODUCT_IMAGES"
    PRODUCT_VIDEO = "PRODUCT_VIDEO"
    PRODUCT_MANUAL = "PRODUCT_MANUAL"
    PRODUCT_CERTIFICATION = "PRODUCT_CERTIFICATION"
    PRODUCT_WARRANTY = "PRODUCT_WARRANTY"
    PRODUCT_DIMENSIONS = "PRODUCT_DIMENSIONS"
    PRODUCT_WEIGHT = "PRODUCT_WEIGHT"
    PRODUCT_COLOR_OPTIONS = "PRODUCT_COLOR_OPTIONS"
    PRODUCT_SIZE_OPTIONS = "PRODUCT_SIZE_OPTIONS"
    PRODUCT_VARIANTS = "PRODUCT_VARIANTS"
    PRODUCT_SKU_INFO = "PRODUCT_SKU_INFO"
    PRODUCT_TAGS = "PRODUCT_TAGS"
    PRODUCT_FAQ = "PRODUCT_FAQ"
    PRODUCT_REVIEWS = "PRODUCT_REVIEWS"
    PRODUCT_AVERAGE_REVIEW = "PRODUCT_AVERAGE_REVIEW"
    PRODUCT_RATING = "PRODUCT_RATING"
    PRODUCT_COMPARISON = "PRODUCT_COMPARISON"
    COMPARE_FEATURE = "COMPARE_FEATURE"
    PRODUCT_ALTERNATIVES = "PRODUCT_ALTERNATIVES"
    RELATED_ACCESSORIES = "RELATED_ACCESSORIES"
    PRODUCT_AVERAGE_PRICE = "PRODUCT_AVERAGE_PRICE"
    VIEW_PRICE_HISTORY = "VIEW_PRICE_HISTORY"
    PRICE_ALERT = "PRICE_ALERT"
    NOTIFY_PRICE_DROP = "NOTIFY_PRICE_DROP"
    NOTIFY_RESTOCK = "NOTIFY_RESTOCK"
    CHECK_STOCK_NEARBY = "CHECK_STOCK_NEARBY"
    CHECK_STOCK_STORE = "CHECK_STOCK_STORE"
    PRODUCT_SHARE = "PRODUCT_SHARE"
    PRODUCT_CUSTOMIZATION = "PRODUCT_CUSTOMIZATION"
    REQUEST_QUOTE = "REQUEST_QUOTE"

    # 3️⃣ CART & WISHLIST MANAGEMENT (3.0)
    ADD_TO_CART = "ADD_TO_CART"
    REMOVE_FROM_CART = "REMOVE_FROM_CART"
    UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY"
    VIEW_CART = "VIEW_CART"
    EMPTY_CART = "EMPTY_CART"
    MOVE_TO_CART = "MOVE_TO_CART"
    SAVE_FOR_LATER = "SAVE_FOR_LATER"
    CART_TOTAL = "CART_TOTAL"
    CART_ITEM_DETAILS = "CART_ITEM_DETAILS"
    APPLY_COUPON = "APPLY_COUPON"
    REMOVE_COUPON = "REMOVE_COUPON"
    VIEW_WISHLIST = "VIEW_WISHLIST"
    ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
    REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"
    VIEW_RECENTLY_VIEWED = "VIEW_RECENTLY_VIEWED"
    CLEAR_RECENTLY_VIEWED = "CLEAR_RECENTLY_VIEWED"
    FAVORITE_BRANDS = "FAVORITE_BRANDS"
    MOVE_TO_WISHLIST = "MOVE_TO_WISHLIST"
    GIFT_WRAP = "GIFT_WRAP"
    ADD_NOTE = "ADD_NOTE"
    CART_SAVING = "CART_SAVING"

    # 4️⃣ CHECKOUT & PAYMENT (4.0)
    CHECKOUT_INITIATE = "CHECKOUT_INITIATE"
    CHECKOUT_ADDRESS = "CHECKOUT_ADDRESS"
    ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS"
    UPDATE_ADDRESS = "UPDATE_ADDRESS"
    DELETE_ADDRESS = "DELETE_ADDRESS"
    CHANGE_ADDRESS = "CHANGE_ADDRESS"
    CHECKOUT_PAYMENT = "CHECKOUT_PAYMENT"
    PAYMENT_OPTIONS = "PAYMENT_OPTIONS"
    CHANGE_PAYMENT_METHOD = "CHANGE_PAYMENT_METHOD"
    UPDATE_PAYMENT_METHOD = "UPDATE_PAYMENT_METHOD"
    CHECKOUT_CONFIRM = "CHECKOUT_CONFIRM"
    PAYMENT_FAILED_HELP = "PAYMENT_FAILED_HELP"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    REFUND_STATUS = "REFUND_STATUS"
    PAYMENT_REFUND = "PAYMENT_REFUND"
    PAYMENT_RECEIPT = "PAYMENT_RECEIPT"
    GIFT_CARD_PURCHASE = "GIFT_CARD_PURCHASE"
    GIFT_CARD_BALANCE = "GIFT_CARD_BALANCE"
    GIFT_CARD_REDEEM = "GIFT_CARD_REDEEM"
    APPLY_GIFT_CARD = "APPLY_GIFT_CARD"

    # 5️⃣ ORDERS & FULFILLMENT (5.0)
    ORDER_STATUS = "ORDER_STATUS"
    ORDER_HISTORY = "ORDER_HISTORY"
    ORDER_CANCEL = "ORDER_CANCEL"
    ORDER_RETURN = "ORDER_RETURN"
    TRACK_SHIPMENT = "TRACK_SHIPMENT"
    TRACK_RETURN = "TRACK_RETURN"
    CANCEL_RETURN = "CANCEL_RETURN"
    REFUND_REQUEST = "REFUND_REQUEST"
    REFUND_COMPLETE = "REFUND_COMPLETE"
    ORDER_INVOICE = "ORDER_INVOICE"
    REORDER = "REORDER"
    DELIVERY_STATUS = "DELIVERY_STATUS"
    DELIVERY_ESTIMATE = "DELIVERY_ESTIMATE"
    SCHEDULE_DELIVERY = "SCHEDULE_DELIVERY"
    CHANGE_DELIVERY_DATE = "CHANGE_DELIVERY_DATE"
    SHIPMENT_DETAILS = "SHIPMENT_DETAILS"
    SHIPPING_COST = "SHIPPING_COST"
    SHIPPING_OPTIONS = "SHIPPING_OPTIONS"
    SHIP_TO_STORE = "SHIP_TO_STORE"
    PICKUP_STORE = "PICKUP_STORE"
    ORDER_MODIFY = "ORDER_MODIFY"

    # 6️⃣ ACCOUNT, AUTH & PROFILE (6.0)
    CREATE_ACCOUNT = "CREATE_ACCOUNT"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    LOGIN_STATUS = "LOGIN_STATUS"
    LOGIN_WITH_SOCIAL = "LOGIN_WITH_SOCIAL"
    FORGOT_PASSWORD = "FORGOT_PASSWORD"
    RESET_PASSWORD = "RESET_PASSWORD"
    CHANGE_PASSWORD = "CHANGE_PASSWORD"
    UPDATE_PROFILE = "UPDATE_PROFILE"
    VIEW_PROFILE = "VIEW_PROFILE"
    DELETE_ACCOUNT = "DELETE_ACCOUNT"
    ACCOUNT_SECURITY = "ACCOUNT_SECURITY"
    TWO_FACTOR_SETUP = "TWO_FACTOR_SETUP"
    TWO_FACTOR_VERIFY = "TWO_FACTOR_VERIFY"
    VERIFY_EMAIL = "VERIFY_EMAIL"
    RESEND_VERIFICATION = "RESEND_VERIFICATION"
    LINK_ACCOUNTS = "LINK_ACCOUNTS"
    UNLINK_ACCOUNT = "UNLINK_ACCOUNT"
    PROFILE_PICTURE_UPDATE = "PROFILE_PICTURE_UPDATE"
    PREFERENCES_UPDATE = "PREFERENCES_UPDATE"

    # 7️⃣ NOTIFICATIONS & SUBSCRIPTIONS (7.0)
    USER_NOTIFICATIONS = "USER_NOTIFICATIONS"
    ENABLE_NOTIFICATIONS = "ENABLE_NOTIFICATIONS"
    DISABLE_NOTIFICATIONS = "DISABLE_NOTIFICATIONS"
    SUBSCRIBE_NEWSLETTER = "SUBSCRIBE_NEWSLETTER"
    UNSUBSCRIBE_NEWSLETTER = "UNSUBSCRIBE_NEWSLETTER"
    NOTIFY_SALES = "NOTIFY_SALES"
    NOTIFY_ORDERS = "NOTIFY_ORDERS"
    NOTIFY_SHIPMENT = "NOTIFY_SHIPMENT"
    NOTIFY_DELIVERY = "NOTIFY_DELIVERY"
    EMAIL_PREFERENCES = "EMAIL_PREFERENCES"
    SMS_PREFERENCES = "SMS_PREFERENCES"
    PUSH_PREFERENCES = "PUSH_PREFERENCES"

    # 8️⃣ SUPPORT, HELP & FAQ (8.0)
    CONTACT_SUPPORT = "CONTACT_SUPPORT"
    LIVE_CHAT = "LIVE_CHAT"
    CALL_SUPPORT = "CALL_SUPPORT"
    REQUEST_CALLBACK = "REQUEST_CALLBACK"
    FEEDBACK_SUBMIT = "FEEDBACK_SUBMIT"
    REPORT_ISSUE = "REPORT_ISSUE"
    REPORT_PRODUCT = "REPORT_PRODUCT"
    HELP_GENERAL = "HELP_GENERAL"
    FAQ_RETURNS = "FAQ_RETURNS"
    FAQ_SHIPPING = "FAQ_SHIPPING"
    FAQ_PAYMENT = "FAQ_PAYMENT"
    FAQ_ACCOUNT = "FAQ_ACCOUNT"
    FAQ_COUPON = "FAQ_COUPON"
    FAQ_TECH_SUPPORT = "FAQ_TECH_SUPPORT"
    FAQ_DELIVERY = "FAQ_DELIVERY"
    FAQ_REFUND = "FAQ_REFUND"
    PAYMENT_HELP = "PAYMENT_HELP"
    SECURITY_HELP = "SECURITY_HELP"

    # 9️⃣ PROMOTIONS, OFFERS & LOYALTY (9.0)
    VIEW_PROMOTIONS = "VIEW_PROMOTIONS"
    VIEW_COUPONS = "VIEW_COUPONS"
    APPLY_PROMO = "APPLY_PROMO"
    REMOVE_PROMO = "REMOVE_PROMO"
    VIEW_BESTSELLERS = "VIEW_BESTSELLERS"
    VIEW_NEW_ARRIVALS = "VIEW_NEW_ARRIVALS"
    VIEW_SALE_COLLECTION = "VIEW_SALE_COLLECTION"
    LOYALTY_POINTS = "LOYALTY_POINTS"
    REDEEM_POINTS = "REDEEM_POINTS"
    CHECK_REWARDS = "CHECK_REWARDS"
    CLAIM_REWARD = "CLAIM_REWARD"
    VIEW_GIFT_OPTIONS = "VIEW_GIFT_OPTIONS"
    PRICE_DROP_ALERTS = "PRICE_DROP_ALERTS"
    FLASH_SALE_INFO = "FLASH_SALE_INFO"

    # 10️⃣ SELLER, MARKETPLACE & CATALOG (10.0)
    VIEW_SELLER_INFO = "VIEW_SELLER_INFO"
    CONTACT_SELLER = "CONTACT_SELLER"
    VIEW_SELLER_RATINGS = "VIEW_SELLER_RATINGS"
    SELLER_POLICIES = "SELLER_POLICIES"
    BULK_ORDER = "BULK_ORDER"
    WHOLESALE_INQUIRY = "WHOLESALE_INQUIRY"
    CORPORATE_ORDER = "CORPORATE_ORDER"
    LIST_PRODUCT = "LIST_PRODUCT"
    UNLIST_PRODUCT = "UNLIST_PRODUCT"
    UPDATE_PRODUCT_LISTING = "UPDATE_PRODUCT_LISTING"
    VERIFY_SELLER = "VERIFY_SELLER"

    # 11️⃣ RETURNS, REFUNDS & WARRANTY (11.0)
    VIEW_RETURN_POLICY = "VIEW_RETURN_POLICY"
    VIEW_WARRANTY_POLICY = "VIEW_WARRANTY_POLICY"
    PRODUCT_RETURN_ELIGIBILITY = "PRODUCT_RETURN_ELIGIBILITY"
    INITIATE_RETURN = "INITIATE_RETURN"
    CANCEL_RETURN = "CANCEL_RETURN"
    TRACK_RETURN = "TRACK_RETURN"
    RETURN_PICKUP_SCHEDULE = "RETURN_PICKUP_SCHEDULE"
    RETURN_STATUS = "RETURN_STATUS"
    WARRANTY_CLAIM = "WARRANTY_CLAIM"
    WARRANTY_STATUS = "WARRANTY_STATUS"

    # 12️⃣ REVIEWS & RATINGS (12.0)
    ADD_REVIEW = "ADD_REVIEW"
    EDIT_REVIEW = "EDIT_REVIEW"
    DELETE_REVIEW = "DELETE_REVIEW"
    FLAG_REVIEW = "FLAG_REVIEW"
    VIEW_REVIEWS = "VIEW_REVIEWS"
    REVIEW_RECOMMENDATION = "REVIEW_RECOMMENDATION"
    PRODUCT_AVERAGE_REVIEW = "PRODUCT_AVERAGE_REVIEW"

    # 13️⃣ ANALYTICS, TRACKING & METRICS (13.0)
    TRACK_USER_ACTION = "TRACK_USER_ACTION"
    TRACK_SEARCH_QUERY = "TRACK_SEARCH_QUERY"
    TRACK_CART_ABANDONMENT = "TRACK_CART_ABANDONMENT"
    VIEW_ANALYTICS = "VIEW_ANALYTICS"
    EXPORT_ANALYTICS = "EXPORT_ANALYTICS"
    LISTEN_BEHAVIOR = "LISTEN_BEHAVIOR"

    # 14️⃣ ACCOUNT PREFERENCES & PERSONALIZATION (14.0)
    SET_LANGUAGE = "SET_LANGUAGE"
    SET_CURRENCY = "SET_CURRENCY"
    SET_ADDRESS_PREFERENCE = "SET_ADDRESS_PREFERENCE"
    SET_PAYMENT_PREFERENCE = "SET_PAYMENT_PREFERENCE"
    MANAGE_ADDRESSES = "MANAGE_ADDRESSES"
    PREFERENCES_EXPORT = "PREFERENCES_EXPORT"
    PREFERENCES_IMPORT = "PREFERENCES_IMPORT"
    PERSONAL_PROFILE_SUMMARY = "PERSONAL_PROFILE_SUMMARY"

    # 15️⃣ SEARCH ADVANCED (15.0)
    SEARCH_ADVANCED = "SEARCH_ADVANCED"
    SEARCH_FUZZY = "SEARCH_FUZZY"
    SEARCH_PHRASE = "SEARCH_PHRASE"
    SEARCH_EXCLUDE = "SEARCH_EXCLUDE"
    SEARCH_BOOLEAN = "SEARCH_BOOLEAN"
    SEARCH_CUSTOM_FILTER = "SEARCH_CUSTOM_FILTER"
    SEARCH_BY_SKU = "SEARCH_BY_SKU"

    # 16️⃣ VOICE, ASSISTANTS & BOT (16.0)
    START_VOICE_SESSION = "START_VOICE_SESSION"
    END_VOICE_SESSION = "END_VOICE_SESSION"
    VOICE_HELP = "VOICE_HELP"
    BOT_HANDOFF = "BOT_HANDOFF"
    BOT_INTENT_CLARIFY = "BOT_INTENT_CLARIFY"
    BOT_FALLBACK = "BOT_FALLBACK"

    # 17️⃣ UI & NAVIGATION (17.0)
    NAV_HOME = "NAV_HOME"
    NAV_CATEGORY = "NAV_CATEGORY"
    NAV_CART = "NAV_CART"
    NAV_WISHLIST = "NAV_WISHLIST"
    NAV_ORDERS = "NAV_ORDERS"
    NAV_PROFILE = "NAV_PROFILE"
    NAV_SEARCH = "NAV_SEARCH"
    NAV_OFFERS = "NAV_OFFERS"
    NAV_HELP = "NAV_HELP"

    # 18️⃣ FILES, DOWNLOADS & ASSETS (18.0)
    DOWNLOAD_INVOICE = "DOWNLOAD_INVOICE"
    DOWNLOAD_MANUAL = "DOWNLOAD_MANUAL"
    DOWNLOAD_RECEIPT = "DOWNLOAD_RECEIPT"
    APP_DOWNLOAD = "APP_DOWNLOAD"
    SHARE_PRODUCT_LINK = "SHARE_PRODUCT_LINK"

    # 19️⃣ PRIVACY, TERMS & LEGAL (19.0)
    PRIVACY_POLICY = "PRIVACY_POLICY"
    TERMS_AND_CONDITIONS = "TERMS_AND_CONDITIONS"
    DATA_REQUEST = "DATA_REQUEST"
    DATA_DELETE_REQUEST = "DATA_DELETE_REQUEST"
    COOKIE_PREFERENCES = "COOKIE_PREFERENCES"

    # 20️⃣ ADMIN, MODERATION & SAFETY (20.0)
    FLAG_CONTENT = "FLAG_CONTENT"
    REVIEW_FLAGGED_CONTENT = "REVIEW_FLAGGED_CONTENT"
    BAN_USER = "BAN_USER"
    UNBAN_USER = "UNBAN_USER"
    GRANT_ADMIN = "GRANT_ADMIN"
    REVOKE_ADMIN = "REVOKE_ADMIN"
    VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS"
    EXPORT_AUDIT_LOGS = "EXPORT_AUDIT_LOGS"
    MODERATION_ACTION = "MODERATION_ACTION"

    # 21️⃣ INTEGRATIONS & THIRD-PARTY (21.0)
    CONNECT_PAYMENT_GATEWAY = "CONNECT_PAYMENT_GATEWAY"
    DISCONNECT_PAYMENT_GATEWAY = "DISCONNECT_PAYMENT_GATEWAY"
    CONNECT_SHIPPING_PROVIDER = "CONNECT_SHIPPING_PROVIDER"
    DISCONNECT_SHIPPING_PROVIDER = "DISCONNECT_SHIPPING_PROVIDER"
    SYNC_INVENTORY = "SYNC_INVENTORY"
    SYNC_ORDERS = "SYNC_ORDERS"

    # 22️⃣ OFFLINE, STORES & PICKUP (22.0)
    STORE_LOCATOR = "STORE_LOCATOR"
    CHECK_STORE_STOCK = "CHECK_STORE_STOCK"
    RESERVE_IN_STORE = "RESERVE_IN_STORE"
    SCHEDULE_PICKUP = "SCHEDULE_PICKUP"
    CANCEL_PICKUP = "CANCEL_PICKUP"

    # 23️⃣ MARKETPLACE FINANCE & INVOICING (23.0)
    REQUEST_INVOICE = "REQUEST_INVOICE"
    SUBMIT_TAX_INFO = "SUBMIT_TAX_INFO"
    VIEW_PAYOUTS = "VIEW_PAYOUTS"
    REQUEST_PAYOUT = "REQUEST_PAYOUT"

    # 24️⃣ MESSAGING & COMMUNICATION (24.0)
    SEND_MESSAGE_TO_SELLER = "SEND_MESSAGE_TO_SELLER"
    VIEW_MESSAGES = "VIEW_MESSAGES"
    DELETE_MESSAGE = "DELETE_MESSAGE"
    MARK_MESSAGE_READ = "MARK_MESSAGE_READ"
    MARK_MESSAGE_UNREAD = "MARK_MESSAGE_UNREAD"

    # 25️⃣ EXPERIMENTS, FEATURES & FLAGS (25.0)
    ENABLE_EXPERIMENT = "ENABLE_EXPERIMENT"
    DISABLE_EXPERIMENT = "DISABLE_EXPERIMENT"
    GET_EXPERIMENT_STATUS = "GET_EXPERIMENT_STATUS"

    # 26️⃣ B2B & ENTERPRISE (26.0)
    REQUEST_CORPORATE_ACCOUNT = "REQUEST_CORPORATE_ACCOUNT"
    VIEW_ENTERPRISE_PRICING = "VIEW_ENTERPRISE_PRICING"
    REQUEST_DEMO = "REQUEST_DEMO"
    ENTERPRISE_BULK_ORDER = "ENTERPRISE_BULK_ORDER"

    # 27️⃣ LOYALTY & MEMBERSHIP (27.0)
    VIEW_MEMBERSHIP = "VIEW_MEMBERSHIP"
    JOIN_MEMBERSHIP = "JOIN_MEMBERSHIP"
    LEAVE_MEMBERSHIP = "LEAVE_MEMBERSHIP"
    MEMBERSHIP_BENEFITS = "MEMBERSHIP_BENEFITS"
    MEMBERSHIP_STATUS = "MEMBERSHIP_STATUS"

    # 28️⃣ SEARCH INSIGHTS & AUTOCOMPLETE (28.0)
    AUTOCOMPLETE_SUGGESTIONS = "AUTOCOMPLETE_SUGGESTIONS"
    SEARCH_SUGGESTION_CLICK = "SEARCH_SUGGESTION_CLICK"
    POPULAR_SEARCH_TERMS = "POPULAR_SEARCH_TERMS"

    # 29️⃣ SEO & LINKS (29.0)
    REQUEST_SEO_FRIENDLY_URL = "REQUEST_SEO_FRIENDLY_URL"
    REPORT_BROKEN_LINK = "REPORT_BROKEN_LINK"

    # 30️⃣ HELPERS, FALLBACKS & UNKNOWN (30.0)
    HELP_CONTEXTUAL = "HELP_CONTEXTUAL"
    HELP_INTENT_EXAMPLE = "HELP_INTENT_EXAMPLE"
    BOT_GREETING = "BOT_GREETING"
    BOT_GOODBYE = "BOT_GOODBYE"
    BOT_THANKS = "BOT_THANKS"
    BOT_ERROR = "BOT_ERROR"
    BOT_CONFIRMATION = "BOT_CONFIRMATION"
    BOT_PROMPT_RETRY = "BOT_PROMPT_RETRY"
    BOT_PROMPT_CONFIRM = "BOT_PROMPT_CONFIRM"

    # 31️⃣ VERY FINE-GRAINED SEARCH & USER ACTIONS (31.0)
    SEARCH_CATEGORY_SUB = "SEARCH_CATEGORY_SUB"
    SEARCH_BY_COLLECTION = "SEARCH_BY_COLLECTION"
    SEARCH_BY_MATERIAL = "SEARCH_BY_MATERIAL"
    SEARCH_BY_THEME = "SEARCH_BY_THEME"
    SEARCH_BY_SEASON = "SEARCH_BY_SEASON"
    SEARCH_BY_OCCASION = "SEARCH_BY_OCCASION"
    FILTER_BY_RETURNABLE = "FILTER_BY_RETURNABLE"
    FILTER_BY_FREE_SHIPPING = "FILTER_BY_FREE_SHIPPING"
    FILTER_BY_EXCHANGE = "FILTER_BY_EXCHANGE"

    # 32️⃣ CART & CHECKOUT EDGE CASES (32.0)
    RESOLVE_CART_CONFLICT = "RESOLVE_CART_CONFLICT"
    MERGE_CARTS = "MERGE_CARTS"
    SAVE_CART = "SAVE_CART"
    RESTORE_SAVED_CART = "RESTORE_SAVED_CART"
    PRICING_DISCREPANCY = "PRICING_DISCREPANCY"
    APPLY_AUTO_DISCOUNT = "APPLY_AUTO_DISCOUNT"

    # 33️⃣ ORDER SUBSCRIPTIONS & RECURRING (33.0)
    SUBSCRIBE_PRODUCT = "SUBSCRIBE_PRODUCT"
    UNSUBSCRIBE_PRODUCT = "UNSUBSCRIBE_PRODUCT"
    SUBSCRIPTION_STATUS = "SUBSCRIPTION_STATUS"
    MANAGE_SUBSCRIPTION = "MANAGE_SUBSCRIPTION"
    PAUSE_SUBSCRIPTION = "PAUSE_SUBSCRIPTION"
    RESUME_SUBSCRIPTION = "RESUME_SUBSCRIPTION"

    # 34️⃣ SECURITY & FRAUD (34.0)
    REPORT_FRAUD = "REPORT_FRAUD"
    FRAUD_DETECTION_HELP = "FRAUD_DETECTION_HELP"
    LOCK_ACCOUNT = "LOCK_ACCOUNT"
    UNLOCK_ACCOUNT = "UNLOCK_ACCOUNT"

    # 35️⃣ DATA, EXPORTS & BACKUPS (35.0)
    EXPORT_ORDERS = "EXPORT_ORDERS"
    EXPORT_CUSTOMERS = "EXPORT_CUSTOMERS"
    EXPORT_PRODUCTS = "EXPORT_PRODUCTS"
    BACKUP_DATA = "BACKUP_DATA"
    RESTORE_DATA = "RESTORE_DATA"

    # 36️⃣ PERSONAL SHOPPING ASSISTANT (36.0)
    ASSISTANT_PROFILE_SETUP = "ASSISTANT_PROFILE_SETUP"
    ASSISTANT_SAVE_PREFERENCES = "ASSISTANT_SAVE_PREFERENCES"
    ASSISTANT_SUGGEST = "ASSISTANT_SUGGEST"
    ASSISTANT_REMINDER = "ASSISTANT_REMINDER"

    # 37️⃣ INTERNATIONALIZATION & TAX (37.0)
    CHECK_TAX = "CHECK_TAX"
    VIEW_TAX_DETAILS = "VIEW_TAX_DETAILS"
    SET_TAX_RESIDENCE = "SET_TAX_RESIDENCE"
    CHECK_IMPORT_DUTY = "CHECK_IMPORT_DUTY"

    # 38️⃣ PAYMENTS — ADVANCED (38.0)
    SPLIT_PAYMENT = "SPLIT_PAYMENT"
    EMI_OPTIONS = "EMI_OPTIONS"
    APPLY_EMI = "APPLY_EMI"
    CANCEL_EMI = "CANCEL_EMI"
    VERIFY_BANK_ACCOUNT = "VERIFY_BANK_ACCOUNT"

    # 39️⃣ OFFLINE MESSAGING & NOTIFICATIONS (39.0)
    SCHEDULE_NOTIFICATION = "SCHEDULE_NOTIFICATION"
    CANCEL_NOTIFICATION = "CANCEL_NOTIFICATION"
    VIEW_NOTIFICATION_HISTORY = "VIEW_NOTIFICATION_HISTORY"

    # 40️⃣ PRODUCT LIFECYCLE (40.0)
    PRODUCT_UPLOAD = "PRODUCT_UPLOAD"
    PRODUCT_UPDATE = "PRODUCT_UPDATE"
    PRODUCT_DELETE = "PRODUCT_DELETE"
    PRODUCT_ARCHIVE = "PRODUCT_ARCHIVE"
    PRODUCT_RESTORE = "PRODUCT_RESTORE"

    # 41️⃣ COUPONS & VOUCHERS (41.0)
    CREATE_COUPON = "CREATE_COUPON"
    EDIT_COUPON = "EDIT_COUPON"
    DELETE_COUPON = "DELETE_COUPON"
    VALIDATE_COUPON = "VALIDATE_COUPON"
    CHECK_COUPON_STATUS = "CHECK_COUPON_STATUS"

    # 42️⃣ FEEDBACK & SURVEYS (42.0)
    SUBMIT_SURVEY = "SUBMIT_SURVEY"
    VIEW_SURVEY_RESULTS = "VIEW_SURVEY_RESULTS"
    REQUEST_FEEDBACK = "REQUEST_FEEDBACK"

    # 43️⃣ DEVICE & APP (43.0)
    REPORT_APP_ISSUE = "REPORT_APP_ISSUE"
    APP_FEEDBACK = "APP_FEEDBACK"
    CHECK_APP_VERSION = "CHECK_APP_VERSION"
    REPORT_CRASH = "REPORT_CRASH"

    # 44️⃣ CONTENT, BLOG & GUIDES (44.0)
    VIEW_BLOG = "VIEW_BLOG"
    SEARCH_BLOG = "SEARCH_BLOG"
    SUBMIT_BLOG_COMMENT = "SUBMIT_BLOG_COMMENT"
    VIEW_GUIDE = "VIEW_GUIDE"

    # 45️⃣ COOPERATIVE & SOCIAL FEATURES (45.0)
    SHARE_WISHLIST = "SHARE_WISHLIST"
    FOLLOW_BRAND = "FOLLOW_BRAND"
    UNFOLLOW_BRAND = "UNFOLLOW_BRAND"
    INVITE_FRIEND = "INVITE_FRIEND"
    APPLY_REFERRAL = "APPLY_REFERRAL"
    VIEW_REFERRAL_STATUS = "VIEW_REFERRAL_STATUS"

    # 46️⃣ BILLING & ACCOUNTING (46.0)
    VIEW_BILLING_HISTORY = "VIEW_BILLING_HISTORY"
    UPDATE_BILLING_INFO = "UPDATE_BILLING_INFO"
    DOWNLOAD_BILL = "DOWNLOAD_BILL"

    # 47️⃣ QA, TEST & DEVOPS (47.0)
    TRIGGER_SMOKE_TEST = "TRIGGER_SMOKE_TEST"
    TRIGGER_LOAD_TEST = "TRIGGER_LOAD_TEST"
    DEPLOY_ROLLBACK = "DEPLOY_ROLLBACK"
    VIEW_DEPLOYMENT_STATUS = "VIEW_DEPLOYMENT_STATUS"

    # 48️⃣ ASSORTMENT & INVENTORY (48.0)
    VIEW_INVENTORY_LEVELS = "VIEW_INVENTORY_LEVELS"
    UPDATE_INVENTORY = "UPDATE_INVENTORY"
    REPORT_STOCK_ISSUE = "REPORT_STOCK_ISSUE"
    INVENTORY_RECONCILE = "INVENTORY_RECONCILE"

    # 49️⃣ HELP & GUIDANCE (49.0)
    GET_START_GUIDE = "GET_START_GUIDE"
    GET_RETURN_INSTRUCTIONS = "GET_RETURN_INSTRUCTIONS"
    GET_WARRANTY_INSTRUCTIONS = "GET_WARRANTY_INSTRUCTIONS"

    # 50️⃣ MISCELLANEOUS VERY FINE-GRAINED (50.0)
    PING = "PING"
    HEALTH_CHECK = "HEALTH_CHECK"
    USER_SESSION_INFO = "USER_SESSION_INFO"
    TIMEZONE_SET = "TIMEZONE_SET"
    LOCALE_SET = "LOCALE_SET"

    # FINAL: Unknown / fallback
    UNKNOWN = "UNKNOWN"

# AUTOMATIC ACTION CODE MAPPING
ACTION_CODE_MAP: Dict[Intent, str] = {
    intent: f"ACT_{intent.value}"
    for intent in Intent
}
